---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: data
  label: Páginas
  create: all
  match: "**/*"
- type: directory
  path: content/service
  label: Nossos Serviços
  create: all
  match: "**/*"
- type: directory
  path: content/portfolio
  label: Portfólio
  create: all
  match: "**/*"
- type: directory
  path: content/contact
  label: Contato
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: Quem Somos
  create: all
  match: "**/*"
- type: heading
  label: Ajustes
- type: document
  path: config.toml
  label: Configuração geral
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
